In [1]:
import numpy as np

In [2]:
arreglo_grados=np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [3]:
arreglo_radianes=arreglo_grados*np.pi/180

In [4]:
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [13]:
random=np.random.randint(10) # de [0,n)
random

6

In [50]:
random_negativo=np.random.randint(-10,10) # de [n,m)
random_negativo

-4

In [51]:
arreglo_random=np.random.randint(10,20,8) #El tercer parametro es el numero de elementos  a generar
arreglo_random

array([14, 19, 10, 10, 19, 18, 13, 13])

In [53]:
otro_random=np.random.rand(4)
otro_random

array([0.49790538, 0.65265224, 0.87588816, 0.62102967])

In [54]:
otro_random2=np.random.rand(4,6)
otro_random2

array([[0.97608878, 0.67300909, 0.14174506, 0.62999597, 0.48909941,
        0.10432444],
       [0.15780419, 0.58750606, 0.48239563, 0.13762575, 0.73672382,
        0.13342415],
       [0.31690728, 0.54657652, 0.30908219, 0.42176523, 0.00225491,
        0.70780629],
       [0.46879263, 0.80305804, 0.25343433, 0.40248786, 0.37780943,
        0.51315652]])

In [55]:
np.average(otro_random) #Promedio

0.6618688629360242

In [57]:
np.mean(otro_random) #media

0.6618688629360242

In [58]:
np.median(otro_random) #mediana

0.6368409564542079

In [59]:
np.std(otro_random) #desviacion estandar

0.13641945454404455

In [60]:
np.var(otro_random) #varianza

0.018610267578094638