In [8]:
import numpy as np

In [9]:
arreglo=np.arange(11)
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arreglo**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [11]:
arreglo[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
arreglo[-6:-1]

array([5, 6, 7, 8, 9])

In [13]:
arreglo[:2]

array([0, 1])

In [14]:
arreglo[:-3]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
arreglo[0:5:2] #con el tercer parametro damo el step

array([0, 2, 4])

In [16]:
arreglo[::-1]#Podemos invertir el arreglo

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [17]:
arreglo[10:2:-2]

array([10,  8,  6,  4])